name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies and start the app in the background
      - name: Install app dependencies and start app
        working-directory: ./app
        run: |
          npm install --force
          nohup npm run dev &  #nohup ensures the process keeps running after the step finishes
          echo $! > server.pid
          sleep 10          # Wait 10 seconds to allow the app to be fully up

      # Install dependencies and run Playwright tests
      - name: Install test dependencies and run Playwright tests
        working-directory: ./testing
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./testing/playwright-report/
          retention-days: 30
